# Generated by Django 4.0.3 on 2022-03-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('wishlist', models.BooleanField()),
                ('sent', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='JobsList',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='job',
            name='jobslist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobslist'),
        ),
    ]
