# Generated by Django 4.0.3 on 2022-03-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_rename_todolist_jobslist_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_filter', models.CharField(max_length=50)),
                ('joblist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobslist')),
            ],
        ),
    ]
