# Generated by Django 4.0.3 on 2022-03-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jobsfilters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedJobs',
            fields=[
                ('jobs_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.jobslist')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistJobs',
            fields=[
                ('jobs_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.jobslist')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobslist',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='jobsfilters',
            name='joblist',
        ),
        migrations.AddField(
            model_name='job',
            name='scraped_jobs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.scrapedjobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='wishlist_jobs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.wishlistjobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsfilters',
            name='scraped_jobs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.scrapedjobs'),
            preserve_default=False,
        ),
    ]
