# Generated by Django 4.0.3 on 2022-03-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_scrapedjobs_wishlistjobs_remove_job_jobslist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scraped_jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.scrapedjobs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='wishlist_jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wishlistjobs'),
        ),
    ]
